Pim\Bundle\CatalogBundle\Entity\AttributeOptionValue:
    type: entity
    table: pim_catalog_attribute_option_value
    fields:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
        locale:
            type: string
            scale: 0
            length: 20
            unique: false
            nullable: true
            precision: 0
            column: locale_code
        value:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
    manyToOne:
        option:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\AttributeOption
            cascade: {  }
            mappedBy: null
            inversedBy: optionValues
            joinColumns:
                option_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
