Pim\Bundle\CatalogBundle\Entity\AttributeRequirement:
    type: entity
    table: pim_catalog_attribute_requirement
    fields:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
        required:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    manyToOne:
        family:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\Family
            cascade: {  }
            mappedBy: null
            inversedBy: requirements
            joinColumns:
                family_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        attribute:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\ProductAttribute
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                attribute_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        channel:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\Channel
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                channel_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
