Pim\Bundle\CatalogBundle\Entity\AttributeOption:
    type: entity
    table: pim_catalog_attribute_option
    repositoryClass: Pim\Bundle\CatalogBundle\Entity\Repository\AttributeOptionRepository
    fields:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
        code:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        default:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: is_default
        translatable:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: is_translatable
        sortOrder:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: sort_order
    manyToOne:
        attribute:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\ProductAttribute
            cascade: {  }
            mappedBy: null
            inversedBy: options
            joinColumns:
                attribute_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        optionValues:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\AttributeOptionValue
            cascade:
                - remove
                - persist
            mappedBy: option
            inversedBy: null
            orphanRemoval: true
            orderBy: null
    lifecycleCallbacks: {  }
