Pim\Bundle\CatalogBundle\Entity\Family:
    type: entity
    table: pim_catalog_family
    repositoryClass: Pim\Bundle\CatalogBundle\Entity\Repository\FamilyRepository
    fields:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
        code:
            type: string
            scale: 0
            length: 100
            unique: true
            nullable: false
            precision: 0
        created:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            gedmo:
                timestampable:
                    on: update
    manyToMany:
        attributes:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\ProductAttribute
            cascade:
                - persist
            mappedBy: null
            inversedBy: null
            joinTable:
                name: pim_catalog_family_attribute
                schema: null
                joinColumns:
                    -
                        name: family_id
                        unique: false
                        nullable: true
                        onDelete: CASCADE
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: attribute_id
                        unique: false
                        nullable: true
                        onDelete: CASCADE
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
    oneToMany:
        translations:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\FamilyTranslation
            cascade:
                - remove
                - persist
            mappedBy: foreignKey
            inversedBy: null
            orphanRemoval: true
            orderBy: null
        requirements:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\AttributeRequirement
            cascade:
                - remove
                - persist
            mappedBy: family
            inversedBy: null
            orphanRemoval: false
            orderBy: null
        products:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\Product
            cascade: {  }
            mappedBy: family
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    manyToOne:
        attributeAsLabel:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\ProductAttribute
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                label_attribute_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
            orphanRemoval: false
    lifecycleCallbacks: {  }
