Pim\Bundle\CatalogBundle\Entity\Group:
    type: entity
    table: pim_catalog_group
    repositoryClass: Pim\Bundle\CatalogBundle\Entity\Repository\GroupRepository
    fields:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
        code:
            type: string
            scale: 0
            length: 50
            unique: true
            nullable: false
            precision: 0
    manyToOne:
        type:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\GroupType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                type_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        attributes:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\ProductAttribute
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinTable:
                name: pim_catalog_group_attribute
                schema: null
                joinColumns:
                    -
                        name: group_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: attribute_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
        products:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\Product
            cascade: {  }
            mappedBy: groups
            inversedBy: null
            joinTable: {  }
            orderBy: null
    oneToMany:
        translations:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\GroupTranslation
            cascade:
                - remove
                - persist
            mappedBy: foreignKey
            inversedBy: null
            orphanRemoval: true
            orderBy: null
    lifecycleCallbacks: {  }
