Pim\Bundle\CatalogBundle\Entity\ProductAssociation:
    type: entity
    table: pim_catalog_product_association
    repositoryClass: Pim\Bundle\CatalogBundle\Entity\Repository\ProductAssociationRepository
    fields:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        association:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\Association
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                association_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        owner:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\Product
            cascade: {  }
            mappedBy: null
            inversedBy: productAssociations
            joinColumns:
                owner_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    manyToMany:
        groups:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\Group
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinTable:
                name: pim_catalog_product_association_group
                schema: null
                joinColumns:
                    -
                        name: productassociation_id
                        unique: false
                        nullable: true
                        onDelete: CASCADE
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: group_id
                        unique: false
                        nullable: true
                        onDelete: CASCADE
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
        products:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\Product
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinTable:
                name: pim_catalog_product_association_product
                schema: null
                joinColumns:
                    -
                        name: productassociation_id
                        unique: false
                        nullable: true
                        onDelete: CASCADE
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: product_id
                        unique: false
                        nullable: true
                        onDelete: CASCADE
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
