Pim\Bundle\CatalogBundle\Entity\ProductAssociation:
    type: entity
    table: pim_catalog_product_association
    repositoryClass: Pim\Bundle\CatalogBundle\Entity\Repository\ProductAssociationRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        ownerId:
            type: integer
            column: owner_id
    manyToOne:
        association:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\Association
            joinColumns:
                association_id:
                    referencedColumnName: id
                    nullable: false
                    onDelete: CASCADE
