services:

    pim_catalog.form.handler.attribute:
        class: %pim_catalog.form.handler.product_attribute.class%
        scope: request
        arguments:
            - '@pim_catalog.form.attribute'
            - '@request'
            - '@doctrine.orm.entity_manager'
            - '@pim_catalog.manager.attribute_type'

    pim_catalog.form.handler.attribute_group:
        class: %pim_catalog.form.handler.attribute_group.class%
        scope: request
        arguments:
            - '@pim_catalog.form.attribute_group'
            - '@request'
            - '@doctrine.orm.entity_manager'

    pim_catalog.form.handler.channel:
        class: %pim_catalog.form.handler.channel.class%
        scope: request
        arguments:
            - '@pim_catalog.form.channel'
            - '@request'
            - '@doctrine.orm.entity_manager'

    pim_catalog.form.handler.currency:
        class: %pim_catalog.form.handler.currency.class%
        scope: request
        arguments:
            - '@pim_catalog.form.currency'
            - '@request'
            - '@doctrine.orm.entity_manager'

    pim_catalog.form.handler.group:
        class: %pim_catalog.form.handler.group.class%
        scope: request
        arguments:
            - '@pim_catalog.form.group'
            - '@request'
            - '@doctrine.orm.entity_manager'

    pim_catalog.form.handler.group_type:
        class: %pim_catalog.form.handler.group_type.class%
        scope: request
        arguments:
            - '@pim_catalog.form.group_type'
            - '@request'
            - '@doctrine.orm.entity_manager'

    pim_catalog.form.handler.association:
        class: %pim_catalog.form.handler.association.class%
        scope: request
        arguments:
            - '@pim_catalog.form.association'
            - '@request'
            - '@doctrine.orm.entity_manager'

    pim_catalog.form.handler.family:
        class: %pim_catalog.form.handler.family.class%
        scope: request
        arguments:
            - '@pim_catalog.form.family'
            - '@request'
            - '@doctrine.orm.entity_manager'
