parameters:
    pim_grid.datagrid.class:                        Pim\Bundle\GridBundle\Datagrid\Datagrid
    pim_grid.builder.datagrid.class:                Pim\Bundle\GridBundle\Builder\ORM\DatagridBuilder
    pim_grid.action.tab_redirect.class:             Pim\Bundle\GridBundle\Action\TabRedirectAction
    pim_grid.action.product_delete.class:           Pim\Bundle\GridBundle\Action\ProductDeleteAction
    pim_grid.routes_registry.class:                 Pim\Bundle\GridBundle\Route\DatagridRouteRegistry
    pim_grid.routes_registry.builder.class:         Pim\Bundle\GridBundle\Route\DatagridRouteRegistryBuilder
    pim_grid.routes_registry.cache_warmer.class:    Pim\Bundle\GridBundle\CacheWarmer\DatagridRouteCacheWarmer
    pim_grid.twig_extension.class:                  Pim\Bundle\GridBundle\Twig\DatagridExtension

    oro_grid.mass_action.dispatcher.class:          Pim\Bundle\GridBundle\Action\MassAction\MassActionDispatcher
    pim_grid.datagrid.helper.class:                 Pim\Bundle\GridBundle\Helper\DatagridHelper

services:
    pim_grid.builder.datagrid:
        class: %pim_grid.builder.datagrid.class%
        arguments:
            - '@form.factory'
            - '@event_dispatcher'
            - '@oro_security.security_facade'
            - '@oro_grid.filter.factory'
            - '@oro_grid.sorter.factory'
            - '@oro_grid.action.factory'
            - %pim_grid.datagrid.class%
            - '@pim_serializer'

    pim_grid.action.tab_redirect:
        class: %pim_grid.action.tab_redirect.class%
        tags:
            - { name: oro_grid.action.type, alias: pim_grid_action_tab_redirect }

    pim_grid.routes_registry.builder:
        class: %pim_grid.routes_registry.builder.class%
        private: true
        lazy: true
        arguments:
            - '@router'

    pim_grid.routes_registry.cache_warmer:
        class: %pim_grid.routes_registry.cache_warmer.class%
        private: true
        arguments:
            - '@pim_grid.routes_registry.builder'
        tags:
            - { name: kernel.cache_warmer }

    pim_grid.routes_registry:
        class: %pim_grid.routes_registry.class%
        arguments:
            - '@router'
            - '@pim_grid.routes_registry.builder'
            - '%kernel.cache_dir%'

    pim_grid.twig_extension:
        class: %pim_grid.twig_extension.class%
        arguments:
            - '@pim_grid.routes_registry'
        tags:
            - { name: twig.extension }

    pim_grid.action.product_delete:
        class: %pim_grid.action.product_delete.class%
        tags:
            - { name: oro_grid.action.type, alias: pim_grid_action_product_delete }

    pim_grid.datagrid.helper:
        class: %pim_grid.datagrid.helper.class%
        arguments:
            - '@service_container'
